### ISSUE TITLE
Overview pages per category

### ISSUE THREAD

**Issue by ewan-escience** [research-software-directory/RSD-as-a-service#1350]
When clicking on a category on a software or project page, you should be redirected to an overview page where you see all software/projects that have that category.

This can be implemented in two stages:

- [x] Add database functionality that generates the metadata for the overviews.
- [x] Create the overviews on the frontend
     - [x] Create categories filter on organisation project page, done in #1394
     - [x] Create categories filter on the organisation software page, done in #1394
     - [x] Create categories filter on the community software page, done in #1394
