### ISSUE TITLE
Anonymously Tracking Page Views with Next.js and Sending Data to Database

### ISSUE THREAD

**Issue by ctwhome** [research-software-directory/RSD-as-a-service#906]
Currently, only users who accept the cookies are eligible to be tracked, complying with GDPR regulations. However, we suspect that a large number of users are using ad blockers (even in some browsers are enabled automatically). We still want to know how many times our pages are viewed, without compromising the anonymity of the users, and just getting a general overview. 

We can implement anonymous tracking of page views in our Next.js application and send the data to our database. This should be implemented by respecting user privacy and complying with regulations like GDPR. 

Tasks:

- [ ] **Create a middleware in Next.js**: We need to utilize Next.js's built-in middleware capabilities to run server-side code before a page is served. This middleware will collect necessary information like the URL of the page being accessed and the anonymized IP of the user. 
- [ ] **Anonymize the IP**: It's crucial to anonymize the IP to ensure user privacy. For IPv4, we can remove the last octet, and for IPv6, we can remove the last 80 bits.
- [ ] **Send the data to the backend service**: The collected data should then be sent to the backend with a POST request.
- [ ] **Store the data in the database**:  Create a new table with metrics?

Below is a simplified version of what the middleware might look like:

```js
import { NextApiRequest, NextApiResponse } from 'next'

export default async function middleware(req: NextApiRequest, res: NextApiResponse) {
  const url = req.url;
  const ip = anonymizeIp(req.headers['x-forwarded-for'] || req.connection.remoteAddress);

  await fetch('https://research-software-directory/api/v1', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      url,
      ip,
    }),
  });

  // Continue to the next middleware or the actual request handler
  return await handler(req, res);
}

function anonymizeIp(ip: string): string {
  if (ip.includes(':')) {
    // IPv6
    return ip.split(':').slice(0, -5).join(':');
  } else {
    // IPv4
    return ip.split('.').slice(0, -1).join('.');
  }
}
```

Please note that the specifics of this implementation can vary depending on our use case and the technologies we're using. Privacy implications of tracking page views, even when done anonymously, must be considered. All relevant laws and regulations should be complied with.

**Comment by jmaassen** [comment]
The method you describe is very similar to what Matomo is already doing? And the user indicated they did not want this. So to what extend are we breaking the law by doing it anyway?

In my opinion, the best we could is only count the number of visitors without storing any IP whatsoever?

**Comment by ewan-escience** [comment]
We've decided that we will keep on using Matomo and not add any other tracking mechanism.
